### ISSUE TITLE
number of datasets

### ISSUE THREAD

**Issue by gouqi666** [tomhosking/separator#11]
hi, I don't know which dataset you use in your paper.  I found there exists  278055/26275/26275 number of data for train/dev/test in training-triples,and have 278055/26275/26275 number of data for train/dev/test in qqp-splitforgeneval. So which dataset you use to reproduce your paper result?

**Comment by tomhosking** [comment]
Hi, the model was trained on the `training-triples` data, and evaluated on `qqp-splitforgeneval`. The training triples are sets of (target, paraphrase, exemplar) triples that are used to learn the separated encoding space, as described in the paper. The `*-splitforgeneval` are sets of (input, references) used to evaluate paraphrase generation at test time.

**Comment by gouqi666** [comment]
Hi, thanks for your reply!!! I'm still puzzled. It looks like you had done a pretraining stage to separate semantic and syntactic before the paraphrase generation task, But the pretraining datasets is part of Quora Question Pairs, So I don't know what datasets I should use if I can't do a pretraining to add your method as my baseline.

**Comment by tomhosking** [comment]
I'm not sure I follow your problem - are you trying to run my model on QQP, or another dataset? If you want to run the model on QQP then there's example code for that here: https://github.com/tomhosking/separator/blob/main/examples/Replication-QQP.ipynb

If you want to train a new model on a different dataset, then there are instructions here: https://github.com/tomhosking/separator#training-a-model-on-a-custom-dataset

I use a separate chunker model to automatically create sets of (target, paraphrase, exemplar) triples from a paraphrasing dataset, which I then use to train the model. At inference time, the code predictor is enabled and predicted syntactic templates are used instead of exemplars. The full details for all of this are of course in the paper.

You may also be interested in the updated version of this model, the code is here: https://github.com/tomhosking/hrq-vae

**Comment by gouqi666** [comment]
okok, I see, you sampled 5 templates per question. Thanks again!!!
